* moved init to entrypoint due to bug https://bugzilla.redhat.com/show_bug.cgi?id=1375661 * removing build directory after "docker build"

diff --git a/assets/init b/assets/init
--- a/assets/init
+++ b/assets/init
@@ -1,46 +1,18 @@
 #!/bin/bash
+set -e
 
-DOCKERHOST=$(ip route show | grep -e ^default | awk -F" " '{ print $3 }')
-
-##
-## setup defaults
-##
-SETUP_DIR="/docker/setup"
-
+BUILD_DIR="/docker/build"
 LOG_DIR="/var/log"
 
-_setupRuntime() {
-    # set up what has to be set up
-    for i in `ls -A ${SETUP_DIR}`; do
-        echo "Setting up $i..."
-        source "${SETUP_DIR}/$i"
-    done
-}
+for i in `ls -A ${BUILD_DIR}`; do
 
+    if [ "$i" == "init" ]; then continue;fi
 
-case "$1" in
-    run)
-        echo "Setting up runtime environment..."
-        _setupRuntime
-        echo "Starting supervisord..."
-        /usr/bin/supervisord -c /etc/supervisor/supervisord.conf
-        tail -f /var/log/supervisor/supervisord.log
-        ;;
-    bash)
-        echo "Starting up bash..."
-        cd ${APP_HOME}
-        /bin/bash
-        ;;
-    *)
-        echo "Setting up runtime environment..."
-        _setupRuntime
-        if [ -x "/docker/scripts/$1" ];then
-            exec su -l ${APP_USER} -c "cd ${APP_HOME};/docker/scripts/$@"
-        else
-            cd ${APP_HOME}
-            su ${APP_USER} -c $@
-        fi;
-        ;;
-esac
+    echo "Building $i..."
 
-exit 0
+    source "${BUILD_DIR}/$i"
+done
+
+# cleanup
+rm -rf /var/lib/apt/lists/*
+rm -rf /var/cache/apt/archives/*
